spring.application.name=iot-backend

# PostgreSQL Database
spring.datasource.url=jdbc:postgresql://localhost:5432/hykon_iot
spring.datasource.username=postgres
spring.datasource.password=sanjaysanthosh08

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# JWT Configuration
jwt.secret=CHANGE_THIS_TO_A_SECURE_SECRET_KEY
jwt.access-token-expiration=900000